services:
  - type: web
    name: ring-world-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    healthCheckPath: /
    envVars:
      - key: PORT
        sync: false
